#!/bin/zsh

## Symlink this file to ~/.zprofile if using xinit to login
## or ~/.profile if use login manager (~/.zprofile also work)

## Script and binaries
export PATH="$HOME/.local/bin:/usr/local/bin:$PATH"
export PATH="$HOME/.local/src/node-v18.16.1-linux-x64/bin:$PATH"

# Session
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway
export MOZ_ENABLE_WAYLAND="1" # Firefox smooth scrolling

## Default programs:
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"
export FMGR="thunar"

## Clean up $HOME
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZPLUGDIR="$HOME/.local/src/zsh_plugins"
export TMUX_CONFIG_DIR="$XDG_CONFIG_HOME/tmux"

## Other program settings:
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export QT_QPA_PLATFORMTHEME="qt5ct" # Use QT on wayland/hyprland

## Autostart sway session
if [ -z "${WAYLAND_DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
	exec sway
fi
