#!/bin/sh
# Custom GRUB color
# Requires executable bit
# /etc/grub.d/99_mytheme
# and run `sudo update-grub`

echo "set menu_color_normal=light-gray/black"
echo "set menu_color_highlight=black/light-gray"
echo "set color_normal=white/black"
echo "set color_highlight=black/white"
